### ISSUE TITLE
Run file iteration

### ISSUE THREAD

**Issue by felipemoraes** [trec-dd/trec-dd-jig#1]
Hi all,
Iterations at run file should be by query right not just by run?

**Comment by graceyang99** [comment]
By run. We only have one initial query

On Thu, Jun 2, 2016 at 9:43 AM, Felipe Moraes notifications@github.com
wrote:

> Hi all,
> Iterations at run file should be by query right not just by run?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/trec-dd/trec-dd-jig/issues/1, or mute the thread
> https://github.com/notifications/unsubscribe/AFIkh6KIW5_me31E_vDA4ion55SW10N-ks5qHt37gaJpZM4IskTu
> .

## 

Cheers
Grace Hui Yang

**Comment by felipemoraes** [comment]
I didn't know that. I thought that we are supposed to run jig for all queries not just one initial only. Is this repository the final jig system?

**Comment by graceyang99** [comment]
Yes, there will be many iterations, but only the first iteration has a
query. For all the subsequent ones, you will receive feedback text with
graded judgments, not a `query' ...

On Thu, Jun 2, 2016 at 11:45 AM, Felipe Moraes notifications@github.com
wrote:

> I didn't know that. I thought that we are supposed to run jig for all
> queries not just one initial only. Is this repository the final jig system?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/trec-dd/trec-dd-jig/issues/1#issuecomment-223333170,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFIkhwAt_xXBBWvviOzzinENq92N9Fxbks5qHvqbgaJpZM4IskTu
> .

## 

Cheers
Grace Hui Yang
